[package]
name = "zisraw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iobase = {path = "../iobase"}
xmltree = "0.10.3"
uuid = "1.1.2"
uom = "0.33.0"
chrono = "0.4.22"
